Repository KU-Taverse/game-server-BE-, pull requests merged in 2024-05, with the labels that each got.

#11 CD 구축
  .github/workflows/deploy.yml
  .github/workflows/pr-test.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/resources/application.yml
Labels: 개발 환경

#12 Feat/deploy
  .github/workflows/deploy.yml
Labels: 개발 환경

#7 Feat/websocket
  .github/workflows/deploy.yml
  build.gradle
  docker-compose.yml
  src/main/java/kutaverse/game/DemoApplication.java
  src/main/java/kutaverse/game/map/config/RedisUserConfiguration.java
  src/main/java/kutaverse/game/map/controller/MapController.java
  src/main/java/kutaverse/game/map/controller/RedisUserController.java
  src/main/java/kutaverse/game/map/controller/UserController.java
  src/main/java/kutaverse/game/map/controller/ViewController.java
  src/main/java/kutaverse/game/map/domain/Status.java
  src/main/java/kutaverse/game/map/domain/User.java
  src/main/java/kutaverse/game/map/dto/MapRequestType.java
  src/main/java/kutaverse/game/map/dto/UserRequestDto.java
  src/main/java/kutaverse/game/map/dto/UserResponseDto.java
  src/main/java/kutaverse/game/map/repository/RedisUserRepository.java
  src/main/java/kutaverse/game/map/repository/UserRepository.java
  src/main/java/kutaverse/game/map/repository/util/RepositoryUtil.java
  src/main/java/kutaverse/game/map/service/RedisUserService.java
  src/main/java/kutaverse/game/map/service/UserService.java
  src/main/java/kutaverse/game/map/websocket/CustomWebSocketHandler.java
  src/main/java/kutaverse/game/map/websocket/MessageSender.java
  src/main/java/kutaverse/game/map/websocket/WebsocketConfig.java
  src/main/java/kutaverse/game/map/websocket/handler/DeleteHandler.java
  src/main/java/kutaverse/game/map/websocket/handler/ResponseHandler.java
  src/main/java/kutaverse/game/map/websocket/handler/SaveHandler.java
  src/main/java/kutaverse/game/map/websocket/handler/WebSocketHandler.java
  src/main/java/kutaverse/game/map/websocket/handler/WebSocketHandlerMapping.java
  src/main/java/kutaverse/game/map/websocket/util/JsonUtil.java
  src/main/resources/templates/index.html
  src/test/java/kutaverse/game/map/unit/RedisUserControllerAPITest.java
  src/test/java/kutaverse/game/map/unit/RedisUserControllerTest.java
Labels: 기능 추가, 자동 배포

#17 [Feat] 미니게임 플레이를 위한 기본 구성 작업
  src/main/java/kutaverse/game/map/controller/MapController.java
  src/main/java/kutaverse/game/minigame/dto/LevelDto.java
  src/main/java/kutaverse/game/minigame/dto/MiniGameRequest.java
  src/main/java/kutaverse/game/minigame/dto/MiniGameRequestType.java
  src/main/java/kutaverse/game/minigame/dto/PositionDto.java
  src/main/java/kutaverse/game/websocket/WebsocketConfig.java
  src/main/java/kutaverse/game/websocket/map/MapWebSocketHandler.java
  src/main/java/kutaverse/game/websocket/map/MessageSender.java
  src/main/java/kutaverse/game/websocket/map/handler/DeleteHandler.java
  src/main/java/kutaverse/game/websocket/map/handler/ResponseHandler.java
  src/main/java/kutaverse/game/websocket/map/handler/SaveHandler.java
  src/main/java/kutaverse/game/websocket/map/handler/WebSocketHandler.java
  src/main/java/kutaverse/game/websocket/map/handler/WebSocketHandlerMapping.java
  src/main/java/kutaverse/game/websocket/map/util/JsonUtil.java
  src/main/java/kutaverse/game/websocket/minigame/GameRoom.java
  src/main/java/kutaverse/game/websocket/minigame/GameRoomManager.java
  src/main/java/kutaverse/game/websocket/minigame/MatchingMaker.java
  src/main/java/kutaverse/game/websocket/minigame/MatchingQueue.java
  src/main/java/kutaverse/game/websocket/minigame/MiniGameWebsocketHandler.java
Labels: 자동 배포
